### ISSUE TITLE
[Bug] Unable to start normally

### ISSUE THREAD

**Issue by 849025143** [flokol120/Spigot-Item-Chest-Sorter#45]
[12:48:09] [Server thread/ERROR] [Minecraft]: Could not load 'plugins\[分类]-ItemChestSorter-1.14.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:315) ~[forge:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[forge:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:304) ~[forge:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:298) ~[forge:1.16.5-3ca3686f]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:209) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:737) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by flokol120** [comment]
@849025143 Which minecraft version are you using? The newest releases need at least 1.18. If you have a lower version you might need to use an older version.

**Comment by flokol120** [comment]
closed due inactivity
